### PR TITLE
Using ALL ROWS for queries

### PR DESCRIPTION
**Pull request by rstribrn**
In case DB default is not used...

### CODE REVIEW

**Comment by xtender** [comment]
It would be better to not change queries, but execute `alter session set optimizer_mode=ALL_ROWS` after connect: hint ALL_ROWS disables FKR (First K-rows) optimization in case of "rownum" in predicates

**Comment by akardapolov** [comment]
Hi @rstribrny 

I propose to set optimizer_mode=ALL_ROWS in session by @xtender's recommendation (for example here https://github.com/akardapolov/ASH-Viewer/blob/master/ashv/src/main/java/gui/connect/ConnectToDbArea.java).

Thanks,
Alex.

**Comment by rstribrn** [comment]
Thank you both for your feedback.

I've reimplemented it the way you suggested => using alter sessions (however for any new connection, per profile type/name).

There are also 2 other minor changes:
- sorted profile names in connection selection dialog.
- some code cleanups here and there.

Tested with DB 19c.

**Comment by akardapolov** [comment]
Well done

**Pull request merged**
